apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- envs:
  - aws-credentials.env
  name: aws-credentials
  type: Opaque
- envs:
  - terraform.env
  name: terraform
  type: Opaque
resources:
- terraform-cli.yaml
- terraform-rosa-sts.yaml
- terraform-rosa-sts-pvc.yaml
namespace: rh-mobb-tf-pipeline
